version: "3.8"

services:
  postgres_db:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - .env_postgres

    
  mongo_db:
    image: mongo
    ports:  
      - "27017:27017"
    env_file:
      - .env_mongo
